apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-envs
data:
  MESSAGE: "Hello world!!!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: jlmenco/sre_app:latest
          imagePullPolicy: Always #sempre faz a atualização da ultima imagem desconsiderando cache
          envFrom:
            - configMapRef:
                name: my-envs
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /Health
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /Health
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 2
          startupProbe:
            httpGet:
              path: /Health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 30
      restartPolicy: Always
